---
- name: Add network interface(s) to a KubeVirt VM and migrate after completion
  hosts: all
  gather_facts: false
  vars:
    name: test01            # VM name
    namespace: vms          # VM namespace
    net_attach_def: "[]"  # Could be "", a single def, or a Python-list string

  tasks:
    - block:
        - name: No attachments defined, create VM only
          ansible.builtin.debug:
            msg: "Create VM completed"
        - name: Exit play when no attachments
          meta: end_play
      when: net_attach_def == '' or net_attach_def == '[]'

    - name: Normalize attach_list_str
      ansible.builtin.set_fact:
        attach_list_str: "{{ (net_attach_def is sequence) and (net_attach_def | join(',')) or (net_attach_def | string | trim('[] ')) }}"

    - name: Turn attach_list_str into list
      ansible.builtin.set_fact:
        attach_list_list: "{{ attach_list_str == '' and [] or attach_list_str.split(',') }}"

    - name: Derive interface names
      ansible.builtin.set_fact:
        interface_names: "{{ attach_list_list | map('split','/') | map('last') | list }}"

    - name: Print planned attachments
      ansible.builtin.debug:
        msg:
          - "net_attach_def: {{ net_attach_def }}"
          - "attachments: {{ attach_list_list }}"
          - "interfaces: {{ interface_names }}"
          
    - name: Add network interface(s) via oc command
      uri:
        url: "{{ lookup('env','K8S_AUTH_HOST') }}/apis/kubevirt.io/v1/namespaces/{{ namespace }}/virtualmachines/{{ name }}"
        method: PATCH
        headers:
          Authorization: "Bearer {{ lookup('env','K8S_AUTH_API_KEY') }}"
          Content-Type: application/json-patch+json
        body: "{{ [
            {'op':'add','path':'/spec/template/spec/networks/-','value':{'name':interface_name,'multus':{'networkName':net_attach}}},
            {'op':'add','path':'/spec/template/spec/domain/devices/interfaces/-','value':{'name':interface_name,'bridge':{},'model':'virtio'}}
          ] | to_json }}"
        status_code: 200
        validate_certs: false
 #       validate_certs: "{{ lookup('env','K8S_AUTH_VERIFY_SSL') | default('true') | bool }}"
      loop: "{{ attach_list_list | zip(interface_names) | list }}"
      loop_control:
        loop_var: pair
        label: "{{ pair[1] }}"
      vars:
        net_attach: "{{ pair[0] }}"
        interface_name: "{{ pair[1] }}"
      register: patch_results

    - name: Show patch results
      ansible.builtin.debug:
        var: patch_results

    - name: Restart VM by toggling runStrategy
      block:
        - name: Set runStrategy to Manual to stop VM
          kubernetes.core.k8s:
            api_version: kubevirt.io/v1
            kind: VirtualMachine
            name: "{{ name }}"
            namespace: "{{ namespace }}"
            merge_type:
              - strategic-merge
            definition:
              spec:
                runStrategy: Manual

        - name: Wait for VMI to terminate
          kubernetes.core.k8s_info:
            api_version: kubevirt.io/v1
            kind: VirtualMachineInstance
            namespace: "{{ namespace }}"
            name: "{{ name }}"
          register: vmi_terminated
          until: vmi_terminated.resources | length == 0
          retries: 10
          delay: 6

        - name: Set runStrategy back to Always to start VM
          kubernetes.core.k8s:
            api_version: kubevirt.io/v1
            kind: VirtualMachine
            name: "{{ name }}"
            namespace: "{{ namespace }}"
            merge_type:
              - strategic-merge
            definition:
              spec:
                runStrategy: Always
      register: restart_runstrategy

    - name: Wait for VM to be Running
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        namespace: "{{ namespace }}"
        name: "{{ name }}"
      register: vmi_restart_info
      until: vmi_restart_info.resources | length > 0 and vmi_restart_info.resources[0].status.phase == 'Running'
      retries: 20
      delay: 6

    - name: Confirm VM restart status
      ansible.builtin.debug:
        msg:
          - "Restart via runStrategy result: {{ restart_runstrategy }}"
          - "VM Status after restart: {{ vmi_restart_info.resources[0].status.phase }}"
