---
- name: "install rhel8 vm"
  hosts: all
  gather_facts: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Print the entire ansible_env dictionary
      debug:
        var: ansible_env
        
    - name: Show what environment variables are available (for debugging)
      debug:
        msg:
          - "FOREMAN_HOST={{ lookup('env','FOREMAN_HOST') }}"
          - "FOREMAN_USERNAME={{ lookup('env','FOREMAN_USERNAME') }}"
          - "FOREMAN_PASSWORD={{ lookup('env','FOREMAN_PASSWORD') }}"

    - name: Create host in Satellite
      theforeman.foreman.host:
        server_url: "{{ lookup('env','FOREMAN_HOST') }}"
        username:   "{{ lookup('env','FOREMAN_USERNAME') }}"
        password:   "{{ lookup('env','FOREMAN_PASSWORD') }}"
        name: "{{ name }}"
        organization: "{{ host_organization }}"
        location: "{{ host_location }}"
        hostgroup: "{{ host_hostgroup }}"
        build: false
        managed: false
        interfaces_attributes:
          - managed: false
            provision: false
      register: created_host

    - name: Display created host details
      debug:
        var: created_host

    - name: Create VirtualMachine
      kubernetes.core.k8s:
        state: present
        template: virtualmachine.yml.j2

    - name: Wait for VM to be ready
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ name }}"
        namespace: "{{ namespace }}"
      register: deploy_collection_vm
      retries: 60
      delay: 10
      until:
      - deploy_collection_vm.resources[0].status is defined
      - deploy_collection_vm.resources[0].status.ready is true

    - name: Wait for VM IP to be populated
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: "{{ name }}"
        namespace: "{{ namespace }}"
      register: deploy_collection_vmi
      retries: 60
      delay: 10
      until: (deploy_collection_vmi.resources[0].status.interfaces[0]['ipAddress'] | default('')) | length > 0
